server:
  port : 9000
spring:
  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.globally_quoted_identifiers: true
      hibernate.globally_quoted_identifiers_skip_column_definitions: true
      hibernate.ddl-auto: create
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.hbm2ddl.auto: create
  datasource:
    main:
      url: jdbc:mysql://127.0.0.1:3306/kotSprings
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialize: true
    test:
      url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
      username: root
      password: password
      driver-class-name: org.h2.Driver